// data.dart
class Elective{
  final String elective;

  Elective(this.elective);
}

class Subject {
  final String name;
  final int? i;
  final String details;
  final List<Elective>? electives;


  Subject(this.name, this.details, {this.i, this.electives});
}

class Semester {
  final String name;
  final List<Subject> subjects;
  final String? subcname;

  Semester(this.name, this.subjects,{ this.subcname});
}

class Branch {
  final String name;
  final List<Semester> semesters;
  final String? docname;

  Branch(this.name, this.semesters,{ this.docname});
}

class Course {
  final String name;
  final List<Branch> branches;

  Course(this.name, this.branches);
}

List<Course> courses = [
  Course('B.Tech', [

    Branch('Electronics and Communication', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', "",i:0),
        Subject('Engineering Physics A - (PHT100)', "",i: 1),
        Subject("Engineering Chemistry - (CYT100)", "",i: 2),
        Subject("Engineering Mechanics - (EST100)", "",i: 3),
        Subject( "Engineering Graphics - (EST110)", "",i: 4),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", "",i: 5),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", "",i: 6),
        Subject("Life Skills - (HUN101)", "",i: 7),
        Subject( "Engineering Physics Lab - (PHL120)", "",i:8),
        Subject("Engineering Chemistry Lab - (CYL120)", "",i: 9),
        Subject("Civil & Mechanical Workshop - (ESL120)", "",i: 10),
        Subject("Electrical & Electronics Workshop - (ESL130)", "",i:11),// Add more subjects
      ],subcname: "sem1"),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", "",i: 0),
        Subject("Engineering Physics A - (PHT100)", "",i: 1),
        Subject("Engineering Chemistry - (CYT100)", "",i: 2),
        Subject("Engineering Mechanics - (EST100)", "",i: 3),
        Subject("Engineering Graphics - (EST110)", "",i: 4),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", "",i: 5),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", "",i: 6),
        Subject("Professional Communication - (HUN102)", "",i: 7),
        Subject("Programming In C - (EST102)", "",i: 8),
        Subject("Engineering Physics Lab - (PHL120)", "",i: 10),
        Subject("Engineering Chemistry Lab - (CYL120)", "",i: 11),
        Subject("Civil & Mechanical Workshop - (ESL120)", "",i: 9),
        Subject("Electrical & Electronics Workshop - (ESL130)", '',i: 12),
        // Add more subjects
      ],subcname: "sem2"),

      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", "",i: 0),
        Subject("Solid State Devices - (ECT201)", "",i: 1),
        Subject("Logic Circuit Design - (ECT203)", "",i: 2),
        Subject("Network Theory - (ECT205)", "", i: 3),
        Subject("Design And Engineering - (EST200)", "",i: 4),
        Subject( "Professional Ethics - (HUT200)", "",i: 5),
        Subject("Sustainable Engineering - (MCN201)", "",i: 6),
      //  Subject("Scientific Computing Lab - (ECL201)", "",i: 7),
      //  Subject("Logic Design Lab - (ECL203)", "",i: 8),
      //  Subject("Remedial/Minor/Honors Course - (VAC) - S3", "",i: 9),
      ],subcname: "sem3"),
      Semester('Semester 4', [
        Subject("Probability, Random Processes And Numerical Methods - (MAT204)", ""),
        Subject("Analog Circuits - (ECT202)", ""),
        Subject("Signals And Systems - (ECT204)", ""),
        Subject("Computer Architecture And Microcontrollers - (ECT206", ""),
        Subject("Design And Engineering - (EST200", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Analog Circuits And Simulation Lab - (ECL202)", ""),
        Subject("Microcontroller Lab - (ECL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ],subcname: "sem4"),
      Semester('Semester 5', [
        Subject("Linear Integrated Circuits - (ECT301)", ""),
        Subject("Digital Signal Processing - (ECT303)", ""),
        Subject("Analog And Digital Communication - (ECT305)", ""),
        Subject("Control Systems - (ECT307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject( "Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Analog Integrated Circuits And Simulation Lab - (ECL331)", ""),
        Subject("Digital Signal Processing Lab - (ECL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ],subcname: "sem5"),
      Semester('Semester 6', [
        Subject("Electromagnetics - (ECT302)", ""),
        Subject("VlSI Circuit Design - (ECT304)", ""),
        Subject("Information Theory And Coding - (ECT306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comprehensive Course Work - (ECT308)", ""),
        Subject("Communication Lab - (ECL332)", ""),
        Subject("Miniproject - (ECD334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ],subcname: "sem6"),
      Semester('Semester 7', [
        Subject("Wireless Communication - (ECT401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Electromagnetics Lab - (ECL411)", ""),
        Subject("Seminar - (ECQ413)", ""),
        Subject("Project Phase I - (ECD415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ],subcname: "sem7"),
      Semester('Semester 8', [
        Subject("Instrumentation - (ECT402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Viva Voce - (ECT404)", ""),
        Subject("Project Phase II - (ECD416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ],subcname: "sem8"),
      // Add more semesters
    ],docname: "ece"),

    Branch('Electrical and Electronics', [

      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ],subcname: "sem1"),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ],subcname: "sem2"),
      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", ""),
        Subject("Circuits And Networks - (EET201)", ""),
        Subject("Measurements And Instrumentation - (EET203)", ""),
        Subject("Analog Electronics - (EET205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Circuits And Measurements Lab - (EEL201)", ""),
        Subject("Analog Electronics Lab - (EEL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ],subcname: "sem3"),
      Semester('Semester 4', [
        Subject("Probability, Random Processes And Numerical Methods - (MAT204)", ""),
        Subject("DC Machines And Transformers - (EET202)", ""),
        Subject("Electromagnetic Theory - (EET204)", ""),
        Subject("Digital Electronics - (EET206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Electrical Machines Lab I - (EEL202)", ""),
        Subject("Digital Electronics Lab - (EEL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ],subcname: "sem4"),
      Semester('Semester 5', [
        Subject("Power Systems I - (EET301)", ""),
        Subject("Microprocessors And Microcontrollers - (EET303)", ""),
        Subject("Signals And Systems - (EET305)", ""),
        Subject("Synchronous And Induction Machines - (EET307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Microprocessors And Microcontrollers Lab - (EEL331)", ""),
        Subject("Electrical Machines Lab II - (EEL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ],subcname: "sem5"),
      Semester('Semester 6', [
        Subject("Linear Control Systems - (EET302)", ""),
        Subject("Power Systems II - (EET304)", ""),
        Subject("Power Electronics - (EET306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comrehensive Course Work - (EET308)", ""),
        Subject("Power Systems Lab - (EEL332)", ""),
        Subject("Power Electronics Lab - (EEL334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ],subcname: "sem6"),
      Semester('Semester 7', [
        Subject("Advanced Control Systems - (EET401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Control Systems Lab - (EEL411)", ""),
        Subject("Seminar - (EEQ413)", ""),
        Subject("Project Phase I - (EED415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ],subcname: "sem7"),
      Semester('Semester 8', [
        Subject("Electrical System Design And Estimation - (EET402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Course Viva - (EET404)", ""),
        Subject("roject Phase II - (EED416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ],subcname: "sem8"),
      // Add semesters and subjects
    ]),
    Branch('Mechanical Engineering', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", ""),
        Subject("Mechanics Of Solids - (MET201)", ""),
        Subject("Mechanics Of Fluids - (MET203)", ""),
        Subject("Metallurgy & Material Science - (MET205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Computer Aided Machine Drawing - (MEL201)", ""),
        Subject("Materials Testing Lab - (MEL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Probability, Statistics And Numerical Methods - (MAT202)", ""),
        Subject("Engineering Thermodynamics - (MET202)", ""),
        Subject("Manufacturing Process - (MET204)", ""),
        Subject("Fluid Machinery - (MET206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Fm & Hm Lab - (MEL202)", ""),
        Subject("Machine Tools Lab-I - (MEL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Mechanics Of Machinery - (MET301)", ""),
        Subject("Thermal Engineering - (MET303)", ""),
        Subject("Industrial & Systems Engineering - (MET305)", ""),
        Subject("Machine Tools And Metrology - (MET307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Machine Tools Lab-II - (MEL331)", ""),
        Subject("Thermal Engineering Lab-I - (MEL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ]),
      Semester('Semester 6', [
        Subject("Heat & Mass Transfer - (MET302)", ""),
        Subject("Dynamics Of Machinery & Machine Design - (MET304)", ""),
        Subject("Advanced Manufacturing Engineering - (MET306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comprehensive Course Work - (MET308)", ""),
        Subject("Computer Aided Design & Analysis Lab - (MEL332)", ""),
        Subject("Thermal Engineering Lab-Ii - (MEL334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ]),
      Semester('Semester 7', [
        Subject("Design Of Machine Elements - (MET401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Mechanical Engineering Lab - (MEL411)", ""),
        Subject("Seminar - (MEQ413)", ""),
        Subject("Project Phase I - (MED415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),
      Semester('Semester 8', [
        Subject("Mechatronics - (MET402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Viva Voce - (MET404)", ""),
        Subject("Project Phase II - (MED416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ]),
      // Add semesters and subjects
    ]),
    Branch('Civil Engineering', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", ""),
        Subject("Mechanics Of Solids - (CET201)", ""),
        Subject("Fluid Mechanics & Hydraulics - (CET203)", ""),
        Subject("Surveying & Geomatics - (CET205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Civil Engineering Planning & Drafting Lab - (CEL201)", ""),
        Subject("Survey Lab - (CEL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Probability, Statistics And Numerical Methods - (MAT202)", ""),
        Subject("Engineering Geology - (CET202)", ""),
        Subject("Geotechnical Engineering - I - (CET204)", ""),
        Subject("Transportation Engineering - (CET206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Material Testing Lab - I - (CEL202)", ""),
        Subject("Fluid Mechanics Lab - (CEL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Structural Analysis – I - (CET301)", ""),
        Subject("Design Of Concrete Structures - (CET303)", ""),
        Subject("Geotechnical Engineering – II - (CET305)", ""),
        Subject("Hydrology & Water Resources Engineering - (CET307)", ""),
        Subject("Construction Technology & Management - (CET309)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Material Testing Lab – II - (CEL331)", ""),
        Subject("Geotechnical Engineering Lab - (CEL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ]),
      Semester('Semester 6', [
        Subject("Structural Analysis – II - (CET302)", ""),
        Subject("Environmental Engineering - (CET304)", ""),
        Subject("Design Of Hydraulic Structures - (CET306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Comprehensive Course Work - (CET308)", ""),
        Subject("Transportation Engineering Lab - (CEL332)", ""),
        Subject("Civil Engineering Software Lab - (CEL334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ]),
      Semester('Semester 7', [
        Subject("Design Of Steel Structures - (CET401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Environmental Engg Lab - (CEL411)", ""),
        Subject("Seminar - (CEQ413)", ""),
        Subject("Project Phase I - (CED415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),
      Semester('Semester 8', [
        Subject("Quantity Surveying & Valuation - (CET402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Viva Voce - (CET404)", ""),
        Subject("Project Phase II - (CED416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),
    ]),
    Branch('Computer Science', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Discrete Mathematical Structures - (MAT203)", ""),
        Subject("Data Structures - (CST201)", ""),
        Subject("Logic System Design - (CST203)", ""),
        Subject("Object Oriented Programming Using Java - (CST205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Data Structures Lab - (CSL201)", ""),
        Subject("Object Oriented Programming Lab (In Java) - (CSL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Graph Theory - (MAT206)", ""),
        Subject("Computer Organisation And Architecture - (CST202", ""),
        Subject("Database Management Systems - (CST204)", ""),
        Subject("Operating Systems - (CST206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Operating Systems Lab - (CSL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Formal Languages And Automata Theory - (CST301)", ""),
        Subject("Computer Networks - (CST303)", ""),
        Subject("System Software - (CST305)", ""),
        Subject("Microprocessors And Microcontrollers - (CST307)", ""),
        Subject("Management Of Software Systems - (CST309)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("System Software And Microprocessors Lab - (CSL331)", ""),
        Subject("Database Management Systems Lab - (CSL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ]),
      Semester('Semester 6', [
        Subject("Compiler Design - (CST302)", ""),
        Subject("Computer Graphics And Image Processing - (CST304)", ""),
        Subject("Algorithm Analysis And Design - (CST306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Comprehensive Course Work - (CST308)", ""),
        Subject("Networking Lab - (CSL332)", ""),
        Subject("Miniproject - (CSD334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ]),
      Semester('Semester 7', [
        Subject("Artificial Intelligence - (CST401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Compiler Lab - (CSL411)", ""),
        Subject("Seminar - (CSQ413)", ""),
        Subject("Project Phase I - (CSD415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),
      Semester('Semester 8', [
        Subject("Distributed Computing - (CST402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Course Viva - (CST404)", ""),
        Subject("Project Phase II - (CSD416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),// Add semesters and subjects
    ]),
    Branch('Industrial Engineering', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [

        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", ""),
        Subject("Theory Of Machines And Design - (IET201)", ""),
        Subject("Fluid Mechanics And Hydraulic Machines - (IET203)", ""),
        Subject("Materials And Manufacturing Processes - (IET205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Fluid Mechanics And Hydraulicmachines Lab - (IEL201)", ""),
        Subject("Materials Testing Lab - (MEL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Introduction To Stochastic Models - (MAT212)", ""),
        Subject("Work System Design - (IET202)", ""),
        Subject("Operations Management - (IET204)", ""),
        Subject("Machine Tools And Digital Manufacturing - (IET206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Work System Design Lab - (IEL202)", ""),
        Subject("Machine Tools Lab - (IEL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Supply Chain And Logistics Management - (IET301)", ""),
        Subject("Operations Research - (IET303)", ""),
        Subject("Thermal Engineering - (IET305)", ""),
        Subject("Object Oriented Programming - (IET307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Thermal Engineering Lab - (IEL331)", ""),
        Subject("Object Oriented Programming Lab - (IEL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ]),
      Semester('Semester 6', [
        Subject("System Modelling And Simulation - (IET302)", ""),
        Subject("Advanced Operations Research - (IET304)", ""),
        Subject("Data Analysis - (IET306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comprehensive Course Work - (IET308)", ""),
        Subject("Simulation Lab - (IEL332)", ""),
        Subject("Data Analysis And Optimisation Lab - (IEL334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ]),
      Semester('Semester 7', [
        Subject("Quality Engineering - (IET401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Quality Control Lab - (IEL411)", ""),
        Subject("Seminar - (IEQ413)", ""),
        Subject("Project Phase 1 - (IED415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),
      Semester('Semester 8', [
        Subject("MCDMT, - (IET402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Viva Voce - (IET404)", ""),
        Subject("Project Phase 2 - (IED416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ]),// Add semesters and subjects
    ]),
    Branch('Applied Electronics and Instrumentation', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [
        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Partial Differential Equation And Complex Analysis - (MAT201)", ""),
        Subject("Solid State Devices - (ECT201)", ""),
        Subject("Logic Circuit Design - (ECT203)", ""),
        Subject("Logic Circuit Design - (ECT203)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Scientific Computing Lab - (ECL201)", ""),
        Subject("Logic Design Lab - (ECL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Probability, Random Processes And Numerical Methods - (MAT204)", ""),
        Subject("Analog Circuits - (ECT202)", ""),
        Subject("Signals And Systems - (ECT204)", ""),
        Subject("Measurements And Instrumentation - (AET206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Analog Circuits And Simulation Lab - (ECL202)", ""),
        Subject("Transducers And Measurements Lab - (AEL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Control Systems - (AET301)", ""),
        Subject("Industrial Instrumentation - (AET303)", ""),
        Subject("Computer Architecture And Embedded Systems - (AET305)", ""),
        Subject("Analog Integrated Circuits - (AET307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Analog Integrated Circuits And Instrumentation Lab - (AEL331)", ""),
        Subject("Embedded Systems Lab - (AEL333)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5", ""),
      ]),
      Semester('Semester 6', [
        Subject("Digital Signal Processing - (AET302)", ""),
        Subject("Process Dynamics And Control - (AET304)", ""),
        Subject("Power Electronics - (AET306)", ""),
        Subject("Elective - I", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comprehensive Course Work - (AET308)", ""),
        Subject("Power Electronics Lab - (AEL332)", ""),
        Subject("Miniproject - (AED334)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S6", ""),
      ]),
      Semester('Semester 7', [
        Subject("Communication Engineering - (AET401)", ""),
        Subject("Elective - II", ""),
        Subject("Elective - Open", ""),
        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Process Control Lab - (AEL411)", ""),
        Subject("Seminar - (AEQ413)", ""),
        Subject("Project Phase I - (AED415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ]),
      Semester('Semester 8', [
        Subject("VLSI Circuit Design - (AET402)", ""),
        Subject("Elective - III", ""),
        Subject("Elective - IV", ""),
        Subject("Elective - V", ""),
        Subject("Comprehensive Course Viva - (AET404)", ""),
        Subject("Project Phase II - (AED416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),// subjects
    ]),
    Branch('Chemical Engineering', [
      Semester('Semester 1', [
        Subject('Linear Algebra And Calculus - (MAT101)', 'Details of Subject 1'),
        Subject('Engineering Physics A - (PHT100)', 'Details of Subject 2'),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject( "Engineering Graphics - (EST110)", ""),
        Subject("Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject("Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Life Skills - (HUN101)", ""),
        Subject( "Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", ""),// Add more subjects
      ]),
      Semester('Semester 2', [
        Subject("Vector Calculus, Differential Equations And Transforms - (MAT102)", ""),
        Subject("Engineering Physics A - (PHT100)", ""),
        Subject("Engineering Chemistry - (CYT100)", ""),
        Subject("Engineering Mechanics - (EST100)", ""),
        Subject("Engineering Graphics - (EST110)", ""),
        Subject( "Basics Of Civil & Mechanical Engineering - (EST120)", ""),
        Subject( "Basics Of Electrical & Electronics Engineering - (EST130)", ""),
        Subject("Professional Communication - (HUN102)", ""),
        Subject("Programming In C - (EST102)", ""),
        Subject("Engineering Physics Lab - (PHL120)", ""),
        Subject("Engineering Chemistry Lab - (CYL120)", ""),
        Subject("Civil & Mechanical Workshop - (ESL120)", ""),
        Subject("Electrical & Electronics Workshop - (ESL130)", 'Details of Subject 3'),
        // Add more subjects
      ]),
      Semester('Semester 3', [
        Subject("Engineering Mathematics - (MAT)", ""),
        Subject("Chemistry For Process Engineering - (CHT201)", ""),
        Subject("Chemical Process Principles - (CHT203)", ""),
        Subject("Fluid And Particle Mechanics - (CHT205)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Sustainable Engineering - (MCN201)", ""),
        Subject("Chemical Technology & Environmental Engineering Lab - (CHL201)", ""),
        Subject("Chemistry Lab For Process Engineering - (CHL203)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S3", ""),
      ]),
      Semester('Semester 4', [
        Subject("Engineering Mathematics - (MAT)", ""),
        Subject("Chemical Engineering Thermodynamics - (CHT202)", ""),
        Subject("Heat Transfer Operations - (CHT204)", ""),
        Subject("Particle Technology - (CHT206)", ""),
        Subject("Design And Engineering - (EST200)", ""),
        Subject("Professional Ethics - (HUT200)", ""),
        Subject("Constitution Of India - (MCN202)", ""),
        Subject("Fluid And Particle Mechanics Lab - (CHL202)", ""),
        Subject("Particle Technology Lab - (CHL204)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC) - S4", ""),
      ]),
      Semester('Semester 5', [
        Subject("Mass Transfer Operations-I - (CHT301)", ""),
        Subject("Environmental Engineering - (CHT303)", ""),
        Subject("Chemical Reaction Engineering - (CHT305)", ""),
        Subject("Instrumentation And Process Control - (CHT307)", ""),
        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Disaster Management - (MCN301)", ""),
        Subject("Heat Transfer Operations Lab - (CHL331)", ""),
        Subject("Process Control Lab - (CHL333)", "",i: 0),
        Subject("Remedial/Minor/Honors Course - (VAC) - S5","",electives:[
          Elective("Occupational Health And Industrial Hygiene - (CHT381)"),
          Elective("Petroleum Refinery Engineering - (CHT383)"),
          Elective("Polymer Technology - (CHT385)"),
          Elective("Advanced Heat Transfer - (CHT393)"),
          Elective("Physico Chemical Methods In Environmental Engineering - (CHT395)"),
          Elective("Soft Computing Techniques - (CHT397)"),
        ]),
      ]),
      Semester('Semester 6', [
        Subject("Mass Transfer Operations-II - (CHT302)", ""),
        Subject("Transport Phenomena - (CHT304)", ""),
        Subject("Chemical Technology - (CHT306)", ""),

        Subject("Elective - I", "", electives:[
          Elective("Biochemical Engineering - (CHT312)"),
          Elective("Energy Engineering - (CHT322)"),
          Elective("Numerical Methods For Process Engineers - (CHT332)"),
          Elective("Material Science And Engineering - (CHT342)"),
          Elective("Operations Research - (CHT352)"),
          Elective("Process Instrumentation - (CHT362)"),
          Elective("Catalyst Science And Catalytic Processes - (CHT372)"),
        ]),

        Subject("Industrial Economics And Foreign Trade - (HUT300)", ""),
        Subject("Management For Engineers - (HUT310)", ""),
        Subject("Comprehensive Course Work - (CHT308)", ""),
        Subject("Mass Transfer Operations Lab - (CHL332)", ""),
        Subject("Chemical Reaction Engineering Lab - (CHL334)", ""),

        Subject("Remedial/Minor/Honors Course - (VAC) - S6", "",electives:[
          Elective("Hazard And Risk Assessment - (CHT382)"),
          Elective("Petrochemical Technology - (CHT384)"),
          Elective("Nano Materials And Nano Technology - (CHT386)"),
          Elective("Chemical Reaction Engineering II - (CHT394)"),
          Elective("Advanced Wastewater Treatment Techniques - (CHT396)"),
          Elective("Modern Control Theory - (CHT398)"),
        ]),

      ]),

      Semester('Semester 7', [
        Subject("Chemical Process Equipment Design I - (CHT401)", ""),

        Subject("Elective - II", "", electives:[
          Elective("Food Processing And Technology - (CHT413)"),
          Elective("Oil And Natural Gas Engineering - (CHT423)"),
          Elective("Process Modelling And Simulation - (CHT433)"),
          Elective("Corrosion Engineering - (CHT443)"),
          Elective("Project Engineering - (CHT453)"),
          Elective("Introduction To Data Analysis - (CHT463)"),
          Elective("Fluidization Engineering - (CHT473)"),
        ]),
        Subject("Elective - Open", "", electives:[
          Elective("Energy Technology And Energy Management - (CHT415)"),
          Elective("Petroleum Resources And Petrochemicals - (CHT425)"),
          Elective("Process Safety Engineering - (CHT435)"),
          Elective("Piping And Pipeline Design For Process Industries - (CHT445)"),
        ]),

        Subject("Industrial Safety Engineering - (MCN401)", ""),
        Subject("Process Simulation Lab - (CHL411)", ""),
        Subject("Seminar - (CHQ413)", ""),
        Subject("Project Phase I - (CHD415)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),

      ]),
      Semester('Semester 8', [
        Subject("Chemical Process Equipment Design II - (CHT402)", ""),
          Subject("Elective - III", "", electives:[
          Elective("Air Pollution Monitoring & Control - (CHT414)"),
          Elective("Petroleum Refinery Engineering - (CHT424)"),
          Elective("Computational Fluid Dynamics - (CHT434)"),
          Elective("Polymer Technology - (CHT444)"),
          Elective("Process Utility And Piping Engineering - (CHT454)"),
          Elective("Drugs And Pharmaceuticals Technology - (CHT464)"),
          Elective("Electrochemical Engineering - (CHT474)"),
        ]),
        Subject("Elective - IV", "", electives:[
          Elective("Economics & Management Of Chemical Industries - (CHT416)"),
          Elective("Petrochemicals And Fertilizers - (CHT426)"),
          Elective("Mathematical Methods In Process Engineering - (CHT436)"),
          Elective("Composite Materials - (CHT446)"),
          Elective("Ceramic Technology - (CHT456)"),
          Elective("Total Quality Management - (CHT466)"),
          Elective("Enzyme Engineering - (CHT476)"),
        ]),
        Subject("Elective - V", "", electives:[
          Elective("Solid Waste Management - (CHT418)"),
          Elective("Nonconventional Petroleum Resources - (CHT428)"),
          Elective("Process Optimization - (CHT438)"),
          Elective("Nanomaterials And Nanotechnology - (CHT448)"),
          Elective("Safety Engineering Of Process Plants - (CHT458)"),
          Elective("Novel Separation Techniques - (CHT468)"),
          Elective("Fuel Cell Technology - (CHT478)"),
        ]),

        Subject("Comprehensive Course Viva - (CHT404)", ""),
        Subject("Project Phase II - (CHD416)", ""),
        Subject("Remedial/Minor/Honors Course - (VAC)", ""),
      ]),//  semesters and subjects
    ]),
    Branch('Aerospace Engineering', [
      Semester('Semester  1', [
        Subject('', ""),
        Subject('', ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 2', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 3', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 4', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 5', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 6', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 7', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 8', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),// Add semesters and subjects
    ]),
    Branch('Information Technology', [
      Semester('Semester  1', [
        Subject('', ""),
        Subject('', ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 2', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 3', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 4', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 5', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 6', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 7', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 8', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),// Add semesters and subjects
    ]),
    Branch('Biotechnology', [
      Semester('Semester  1', [
        Subject('', ""),
        Subject('', ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 2', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 3', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 4', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 5', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 6', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 7', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),
      Semester('Semester 8', [
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
        Subject("", ""),
      ]),// Add semesters and subjects
    ]),
  ]),

  Course('B.Arch', [
    Branch('Program 1', [
      Semester('Semester 1', [
        Subject('Subject 1', 'Details of Subject 1'),
        Subject('Subject 2', 'Details of Subject 2'),
        // Add more subjects
      ]),
      Semester('Semester 2', [
        Subject('Subject 3', 'Details of Subject 3'),
        // Add more subjects
      ]),// Add semesters and subjects
    ]),
    Branch('Program 2', [
      // Add semesters and subjects
    ]),
    Branch('Program 3', [
      // Add semesters and subjects
    ]),
    Branch('Program 4', [
      // Add semesters and subjects
    ]),
  ]),

  Course('B.Des', [
    Branch('Program 1', [
      Semester('Semester 1', [
        Subject('Subject 1', 'Details of Subject 1'),
        Subject('Subject 2', 'Details of Subject 2'),
        // Add more subjects
      ]),
      Semester('Semester 2', [
        Subject('Subject 3', 'Details of Subject 3'),
        // Add more subjects
      ]), // Add semesters and subjects
    ]),

  ]),
];
